server:
  port: 8000

spring:
  application:
    name: blood-bank-api-gateway

zuul:
  ignoredServices: '*'
  routes:
    ms-one-bank-a:
      path: /ms-one-bank-a/**
      service-id: ms-one-bank-a
      stripPrefix: true
    ms-two-bank-b:
      path: /ms-two-bank-b/**
      serviceId: ms-two-bank-b
      stripPrefix: true
endpoints:
  routes:
    sensitive: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
